name: Tests

on:
  pull_request:
    branches: [ main, develop ]
    
jobs:
  test:
    name: Run All Tests
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Tests
        run: |
         xcodebuild test \
          -project "Sport Results/Sport Results.xcodeproj" \
          -scheme "Sport Results" \
          -testPlan "AllTests" \
          -destination "platform=iOS Simulator,name=iPhone 16,OS=latest" \
          -parallel-testing-enabled YES
